---
- name: Install required packages
  apt:
    name:
      - apache2
      - postgresql-client
    update_cache: yes
    state: present

- name: Enable and start Apache
  systemd:
    name: apache2
    enabled: yes
    state: started

- name: Create HTML directory
  file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: Fetch data from PostgreSQL and write to index.html
  shell: |
    export PGPASSWORD={{ db_password }}
    echo "<h1>Hello from Terraform Web Server</h1>" > /var/www/html/index.html
    echo "<h2>Fetched from DB:</h2>" >> /var/www/html/index.html
    psql -h {{ db_host }} -U {{ db_user }} -d mydb -t -c "SELECT content FROM mytable;" >> /var/www/html/index.html
  args:
    executable: /bin/bash

